version: "3.8"

services:
    jenkins:
        image: jenkins/jenkins:lts
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - jenkins_home:/var/jenkins_home
        networks:
            - jenkins-net

    test-target:
        image: alpine:latest
        command: tail -f /dev/null # Keep the container running
        networks:
            - jenkins-net

volumes:
    jenkins_home:

networks:
    jenkins-net:
